apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
    - name: websrv-img
      image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/websrv-img:webserver_version_1
      env:
        - name: DBPWD
          value: pw
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
