apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
    - name: websrv-img
      image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/kennith-webapp-ecr-repo:application-v0.1
      env:
        - name: DBPWD
          value: "12345"
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql-service.sqldb"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
