apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: sqldb
spec:
  containers:
    - name: mysql-img   # Updated container name
      image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/mysql-img
      env:
        - name: mysql_secret_key
          value: "12345"
      ports:
        - containerPort: 3306
