apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: sqldb
spec:
  selector:
    app: mysql
    type: ClusterIP
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306